esphome:
  name: sht30-espnow
esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino
# logger:

# import the components
external_components:
  - source:
      type: git
      url: https://github.com/u-fire/ESPHomeComponents/

# no need for api or wifi block when using just ESP-Now
globals:
  - id: sent
    type: int
    restore_value: no
    initial_value: '0'

now_mqtt:
  on_sent:
    then:
      - lambda: id(sent)++; 
      - if:
          condition:
            lambda: 'return id(sent) == 4;'
          then:
            - lambda: id(sent) = 0;
          - deep_sleep.enter:
              id: sleep_
              sleep_duration: 5min

deep_sleep:
  id: sleep_

i2c:
  sda: 10
  scl: 20

sensor:
  - platform: sht3xd
    id: sht
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    address: 0x44
    update_interval: 10s

  - platform: adc
    id: adc_
    name: "Battery voltage"
    unit_of_measurement: "V"
    pin: GPIO3
    update_interval: 10s
    attenuation: auto
    filters:
      - multiply: 2.0
      - offset: 0.2

  - platform: copy
    source_id: adc_
    device_class: BATTERY
    name: "Battery"
    unit_of_measurement: "%"
    filters:
    - calibrate_linear:
      - 3.6 -> 5
      - 4.1 -> 100
    - lambda: return 30*round(x/30);