substitutions:
  friendly_name: Microfire Mod-ORP
  device_name: microfire-mod-orp
esphome:
  name: $device_name
esp32:
  board: esp32dev
  framework:
    type: arduino
logger:
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: $device_name
    password: !secret wifi_failover
captive_portal:

# import the mod-orp component
external_components:
  - source:
      type: git
      url: https://github.com/u-fire/ESPHomeComponents/

# https://esphome.io/components/i2c.html
i2c:
  sda: 21
  scl: 22

sensor:
  - platform: mod_orp
    id: orp
    name: ORP

button:
  - platform: template
    id: orp_calibrate_low
    name: ORP Calibrate Single 400 mV
    icon: mdi:format-vertical-align-center
    on_press:
        lambda: |-
          id(orp).calibrateSingle(400);
  
  - platform: template
    id: orp_calibrate_reset
    name: ORP Calibrate Reset
    icon: mdi:restore
    on_press:
        lambda: |-
          id(orp).calibrateReset();

  - platform: factory_reset
    name: Restart with Factory Default Settings