substitutions:
  friendly_name: Microfire Mod-NTC
  device_name: microfire-mod-ntc
esphome:
  name: $device_name
esp32:
  board: esp32dev
  framework:
    type: arduino
logger:
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: $device_name
    password: !secret wifi_failover
captive_portal:

# import the mod-ntc component
external_components:
  - source:
      type: git
      url: https://github.com/u-fire/ESPHomeComponents/

# https://esphome.io/components/i2c.html
i2c:
  sda: 21
  scl: 22

sensor:
  - platform: mod_ntc
    id: ntc
    name: Temperature
    beta: 3950

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
